config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :step_set_subscriptions, only: %i[new create show]

  post "/step_set_subscriptions/update", to: "step_set_subscriptions#update"

  get "monitors/lb"
  get "monitors/commit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :step_set
end

app/models/step_set.rb
class StepSet < ApplicationRecord
  has_many :steps
end

app/models/step_set_subscription.rb
# frozen_string_literal: true

class StepSetSubscription < ApplicationRecord
  belongs_to :step_set, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monitors_controller.rb
# frozen_string_literal: true

class MonitorsController < ApplicationController
  protect_from_forgery with: :exception

  layout nil

  def lb
    ActiveRecord::Migration.check_pending!
    render plain: File.read(Rails.public_path.join("lb.txt"))
  rescue ActiveRecord::PendingMigrationError
    render plain: "PENDING MIGRATIONS", status: :service_unavailable
  end

  def commit
    render plain: ENV["GIT_COMMIT"]
  end
end

app/controllers/step_set_subscriptions_controller.rb
# frozen_string_literal: true

class StepSetSubscriptionsController < ApplicationController
  TWILIO_FROM_NUMBER = ENV["TWILIO_FROM_NUMBER"] || Rails.application.credentials.twilio[:from_number]
  TWILIO_FLOW_ID = ENV["TWILIO_FLOW_ID"] || Rails.application.credentials.twilio[:flow_id]
  TWILIO_ACCOUNT_SID = ENV["TWILIO_ACCOUNT_SID"] || Rails.application.credentials.twilio[:account_sid]
  TWILIO_AUTH_TOKEN = ENV["TWILIO_AUTH_TOKEN"] || Rails.application.credentials.twilio[:auth_token]

  STEP_DESCRIPTION = "Encourage your friend by asking if you can pray for them."

  skip_before_action :verify_authenticity_token, only: [:update]

  def new
    @step_description = step_description
  end

  def create
    resp = create_twilio_session
    StepSetSubscription.create(step_set: step&.step_set, execution_sid: resp.sid)

    redirect_to step_set_subscription_path(1)
  end

  def show
  end

  def update
    sub = StepSetSubscription.find_by(execution_sid: params[:sid])
    sub&.update(status: params[:status])
    render plain: "OK"
  end

  private

  def create_twilio_session
    flow = client.studio.v1.flows(TWILIO_FLOW_ID)
    flow.executions.create(from: TWILIO_FROM_NUMBER,
                           to: params[:phone_number],
                           parameters: {step: step_description}.to_json)
  end

  def client
    Twilio::REST::Client.new(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
  end

  def step
    Step.find_by(id: params[:step_id]) if params[:step_id]
  end

  def step_description
    step&.body || STEP_DESCRIPTION
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>StepInvitationPlatform</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap" rel="stylesheet">
  <% if Rails.env.staging? %>
  <script src="//assets.adobedtm.com/launch-EN5d806cd3bf634b52a8ee5387e783444d-development.min.js" async></script>
  <% end %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/step_set_subscriptions/new.html.erb
<div class='step-container'>
  <div class='step'>
    <%= image_tag 'small-logo.png', width: '67px' %>
    <div class='text'>
      <h2>a faith step to take:</h2>
      <h1><%= @step_description %></h1>
    </div>
  </div>
  <div class='triangle'></div>
</div>
<div class='new-subscription-container'>
  <div class='calling-message'>
    <h2>It’s time for action!</h2>
    <p>Let us help you take steps of faith with our new <%= image_tag 'text-steps-logo.png', width: '165px' %></p>
  </div>

  <%= form_tag step_set_subscriptions_path, class: 'form' do %>
    <%= hidden_field_tag :step_id, params[:step_id] %>
    <div class='form-row'>
      <%= label_tag :phone_number, 'Mobile Phone', class: 'hidden' %>
      <%= text_field_tag :phone_number, '', required: true, placeholder: '📞Mobile Phone' %>
      <%= submit_tag 'remind me' %>
    </div>
    <p>We don’t like spam and we promise not to share your phone number</p>
  <% end %>
</div>

app/views/step_set_subscriptions/show.html.erb
<div class='new-subscription-container'>
  <h2 class='success-message'>Awesome, we're sending you more info now!</h2>
</div>